# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sesa.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1115, 734)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.button_letsgo = QtGui.QPushButton(self.centralwidget)
        self.button_letsgo.setGeometry(QtCore.QRect(900, 650, 151, 31))
        self.button_letsgo.setCheckable(False)
        self.button_letsgo.setObjectName(_fromUtf8("button_letsgo"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(555, 20, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.button_quit = QtGui.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(740, 650, 151, 31))
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.source = QtGui.QComboBox(self.centralwidget)
        self.source.setGeometry(QtCore.QRect(620, 56, 111, 31))
        self.source.setObjectName(_fromUtf8("source"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 60, 81, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.mode = QtGui.QComboBox(self.centralwidget)
        self.mode.setGeometry(QtCore.QRect(620, 90, 111, 31))
        self.mode.setObjectName(_fromUtf8("mode"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 90, 81, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 30, 101, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.N_Markers = QtGui.QSpinBox(self.centralwidget)
        self.N_Markers.setGeometry(QtCore.QRect(420, 30, 60, 31))
        self.N_Markers.setObjectName(_fromUtf8("N_Markers"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(560, 30, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 20, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 440, 121, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 0, 481, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(480, 10, 20, 521))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 10, 20, 521))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 480, 121, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 69, 301, 334))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.grid_imu = QtGui.QGridLayout(self.gridLayoutWidget)
        self.grid_imu.setMargin(0)
        self.grid_imu.setObjectName(_fromUtf8("grid_imu"))
        self.pos_IMU_5 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_5.setDecimals(6)
        self.pos_IMU_5.setMaximum(9.0)
        self.pos_IMU_5.setSingleStep(0.001)
        self.pos_IMU_5.setObjectName(_fromUtf8("pos_IMU_5"))
        self.grid_imu.addWidget(self.pos_IMU_5, 5, 1, 1, 1)
        self.seg_7 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_7.setMinimum(1)
        self.seg_7.setMaximum(8)
        self.seg_7.setObjectName(_fromUtf8("seg_7"))
        self.grid_imu.addWidget(self.seg_7, 7, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.grid_imu.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.grid_imu.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.grid_imu.addWidget(self.label_13, 8, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.grid_imu.addWidget(self.label_10, 1, 0, 1, 1)
        self.pos_IMU_1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_1.setDecimals(6)
        self.pos_IMU_1.setMaximum(9.0)
        self.pos_IMU_1.setSingleStep(0.001)
        self.pos_IMU_1.setObjectName(_fromUtf8("pos_IMU_1"))
        self.grid_imu.addWidget(self.pos_IMU_1, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.grid_imu.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.grid_imu.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.grid_imu.addWidget(self.label_16, 6, 0, 1, 1)
        self.pos_IMU_7 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_7.setDecimals(6)
        self.pos_IMU_7.setMaximum(9.0)
        self.pos_IMU_7.setSingleStep(0.001)
        self.pos_IMU_7.setObjectName(_fromUtf8("pos_IMU_7"))
        self.grid_imu.addWidget(self.pos_IMU_7, 7, 1, 1, 1)
        self.pos_IMU_2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_2.setDecimals(6)
        self.pos_IMU_2.setMaximum(9.0)
        self.pos_IMU_2.setSingleStep(0.001)
        self.pos_IMU_2.setObjectName(_fromUtf8("pos_IMU_2"))
        self.grid_imu.addWidget(self.pos_IMU_2, 2, 1, 1, 1)
        self.seg_1 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_1.setMinimum(1)
        self.seg_1.setMaximum(8)
        self.seg_1.setObjectName(_fromUtf8("seg_1"))
        self.grid_imu.addWidget(self.seg_1, 1, 2, 1, 1)
        self.seg_8 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_8.setMinimum(1)
        self.seg_8.setMaximum(8)
        self.seg_8.setObjectName(_fromUtf8("seg_8"))
        self.grid_imu.addWidget(self.seg_8, 8, 2, 1, 1)
        self.pos_IMU_6 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_6.setDecimals(6)
        self.pos_IMU_6.setMaximum(9.0)
        self.pos_IMU_6.setSingleStep(0.001)
        self.pos_IMU_6.setObjectName(_fromUtf8("pos_IMU_6"))
        self.grid_imu.addWidget(self.pos_IMU_6, 6, 1, 1, 1)
        self.pos_IMU_3 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_3.setDecimals(6)
        self.pos_IMU_3.setMaximum(9.0)
        self.pos_IMU_3.setSingleStep(0.001)
        self.pos_IMU_3.setObjectName(_fromUtf8("pos_IMU_3"))
        self.grid_imu.addWidget(self.pos_IMU_3, 3, 1, 1, 1)
        self.seg_3 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_3.setMinimum(1)
        self.seg_3.setMaximum(8)
        self.seg_3.setObjectName(_fromUtf8("seg_3"))
        self.grid_imu.addWidget(self.seg_3, 3, 2, 1, 1)
        self.pos_IMU_8 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_8.setDecimals(6)
        self.pos_IMU_8.setMaximum(9900.0)
        self.pos_IMU_8.setObjectName(_fromUtf8("pos_IMU_8"))
        self.grid_imu.addWidget(self.pos_IMU_8, 8, 1, 1, 1)
        self.seg_2 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_2.setMinimum(1)
        self.seg_2.setMaximum(8)
        self.seg_2.setObjectName(_fromUtf8("seg_2"))
        self.grid_imu.addWidget(self.seg_2, 2, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.grid_imu.addWidget(self.label_15, 7, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.grid_imu.addWidget(self.label_17, 5, 0, 1, 1)
        self.seg_5 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_5.setMinimum(1)
        self.seg_5.setMaximum(8)
        self.seg_5.setObjectName(_fromUtf8("seg_5"))
        self.grid_imu.addWidget(self.seg_5, 5, 2, 1, 1)
        self.pos_IMU_4 = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_IMU_4.setDecimals(6)
        self.pos_IMU_4.setMaximum(9.0)
        self.pos_IMU_4.setSingleStep(0.001)
        self.pos_IMU_4.setObjectName(_fromUtf8("pos_IMU_4"))
        self.grid_imu.addWidget(self.pos_IMU_4, 4, 1, 1, 1)
        self.seg_4 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_4.setMinimum(1)
        self.seg_4.setMaximum(8)
        self.seg_4.setObjectName(_fromUtf8("seg_4"))
        self.grid_imu.addWidget(self.seg_4, 4, 2, 1, 1)
        self.seg_6 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seg_6.setMinimum(1)
        self.seg_6.setMaximum(8)
        self.seg_6.setObjectName(_fromUtf8("seg_6"))
        self.grid_imu.addWidget(self.seg_6, 6, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.grid_imu.addWidget(self.label_20, 0, 2, 1, 1)
        self.imuActivate_1 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_1.setText(_fromUtf8(""))
        self.imuActivate_1.setObjectName(_fromUtf8("imuActivate_1"))
        self.grid_imu.addWidget(self.imuActivate_1, 1, 3, 1, 1)
        self.imuActivate_2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_2.setText(_fromUtf8(""))
        self.imuActivate_2.setObjectName(_fromUtf8("imuActivate_2"))
        self.grid_imu.addWidget(self.imuActivate_2, 2, 3, 1, 1)
        self.imuActivate_3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_3.setText(_fromUtf8(""))
        self.imuActivate_3.setObjectName(_fromUtf8("imuActivate_3"))
        self.grid_imu.addWidget(self.imuActivate_3, 3, 3, 1, 1)
        self.imuActivate_4 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_4.setText(_fromUtf8(""))
        self.imuActivate_4.setObjectName(_fromUtf8("imuActivate_4"))
        self.grid_imu.addWidget(self.imuActivate_4, 4, 3, 1, 1)
        self.imuActivate_5 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_5.setText(_fromUtf8(""))
        self.imuActivate_5.setObjectName(_fromUtf8("imuActivate_5"))
        self.grid_imu.addWidget(self.imuActivate_5, 5, 3, 1, 1)
        self.imuActivate_6 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_6.setText(_fromUtf8(""))
        self.imuActivate_6.setObjectName(_fromUtf8("imuActivate_6"))
        self.grid_imu.addWidget(self.imuActivate_6, 6, 3, 1, 1)
        self.imuActivate_7 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_7.setText(_fromUtf8(""))
        self.imuActivate_7.setObjectName(_fromUtf8("imuActivate_7"))
        self.grid_imu.addWidget(self.imuActivate_7, 7, 3, 1, 1)
        self.imuActivate_8 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imuActivate_8.setText(_fromUtf8(""))
        self.imuActivate_8.setObjectName(_fromUtf8("imuActivate_8"))
        self.grid_imu.addWidget(self.imuActivate_8, 8, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.grid_imu.addWidget(self.label_19, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(320, 80, 187, 317))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.grid_marker = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.grid_marker.setMargin(0)
        self.grid_marker.setObjectName(_fromUtf8("grid_marker"))
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.grid_marker.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.grid_marker.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.grid_marker.addWidget(self.label_31, 5, 0, 1, 1)
        self.marker_8 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_8.setDecimals(6)
        self.marker_8.setMaximum(9.0)
        self.marker_8.setSingleStep(0.001)
        self.marker_8.setObjectName(_fromUtf8("marker_8"))
        self.grid_marker.addWidget(self.marker_8, 8, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.grid_marker.addWidget(self.label_23, 8, 0, 1, 1)
        self.marker_4 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_4.setDecimals(6)
        self.marker_4.setMaximum(9.0)
        self.marker_4.setSingleStep(0.001)
        self.marker_4.setObjectName(_fromUtf8("marker_4"))
        self.grid_marker.addWidget(self.marker_4, 4, 1, 1, 1)
        self.marker_2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_2.setDecimals(6)
        self.marker_2.setMaximum(9.0)
        self.marker_2.setSingleStep(0.001)
        self.marker_2.setObjectName(_fromUtf8("marker_2"))
        self.grid_marker.addWidget(self.marker_2, 2, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.grid_marker.addWidget(self.label_29, 6, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.grid_marker.addWidget(self.label_24, 1, 0, 1, 1)
        self.marker_6 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_6.setDecimals(6)
        self.marker_6.setMaximum(9.0)
        self.marker_6.setSingleStep(0.001)
        self.marker_6.setObjectName(_fromUtf8("marker_6"))
        self.grid_marker.addWidget(self.marker_6, 6, 1, 1, 1)
        self.marker_5 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_5.setDecimals(6)
        self.marker_5.setMaximum(9.0)
        self.marker_5.setSingleStep(0.001)
        self.marker_5.setObjectName(_fromUtf8("marker_5"))
        self.grid_marker.addWidget(self.marker_5, 5, 1, 1, 1)
        self.marker_3 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_3.setDecimals(6)
        self.marker_3.setMaximum(9.0)
        self.marker_3.setSingleStep(0.001)
        self.marker_3.setObjectName(_fromUtf8("marker_3"))
        self.grid_marker.addWidget(self.marker_3, 3, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.grid_marker.addWidget(self.label_30, 7, 0, 1, 1)
        self.marker_1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_1.setDecimals(6)
        self.marker_1.setMaximum(9.0)
        self.marker_1.setSingleStep(0.001)
        self.marker_1.setObjectName(_fromUtf8("marker_1"))
        self.grid_marker.addWidget(self.marker_1, 1, 1, 1, 1)
        self.marker_7 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.marker_7.setDecimals(6)
        self.marker_7.setMaximum(9.0)
        self.marker_7.setSingleStep(0.001)
        self.marker_7.setObjectName(_fromUtf8("marker_7"))
        self.grid_marker.addWidget(self.marker_7, 7, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.grid_marker.addWidget(self.label_25, 4, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.grid_marker.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.grid_marker.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(210, 410, 301, 41))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 520, 521, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(500, 10, 251, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(500, 130, 251, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(740, 20, 20, 121))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(490, 20, 20, 121))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(730, 290, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.arm_length = QtGui.QDoubleSpinBox(self.centralwidget)
        self.arm_length.setGeometry(QtCore.QRect(130, 440, 91, 31))
        self.arm_length.setDecimals(6)
        self.arm_length.setSingleStep(0.001)
        self.arm_length.setObjectName(_fromUtf8("arm_length"))
        self.arm_radius = QtGui.QDoubleSpinBox(self.centralwidget)
        self.arm_radius.setGeometry(QtCore.QRect(130, 480, 91, 31))
        self.arm_radius.setDecimals(6)
        self.arm_radius.setSingleStep(0.001)
        self.arm_radius.setObjectName(_fromUtf8("arm_radius"))
        self.play_file = QtGui.QLineEdit(self.centralwidget)
        self.play_file.setGeometry(QtCore.QRect(550, 370, 221, 31))
        self.play_file.setObjectName(_fromUtf8("play_file"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(610, 330, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.record_file = QtGui.QLineEdit(self.centralwidget)
        self.record_file.setGeometry(QtCore.QRect(830, 370, 211, 31))
        self.record_file.setObjectName(_fromUtf8("record_file"))
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(520, 370, 31, 31))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(900, 330, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(800, 370, 31, 31))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.play_rate = QtGui.QDoubleSpinBox(self.centralwidget)
        self.play_rate.setGeometry(QtCore.QRect(580, 420, 141, 31))
        self.play_rate.setDecimals(4)
        self.play_rate.setSingleStep(0.01)
        self.play_rate.setObjectName(_fromUtf8("play_rate"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(530, 410, 41, 51))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.play_start = QtGui.QDoubleSpinBox(self.centralwidget)
        self.play_start.setGeometry(QtCore.QRect(640, 470, 81, 31))
        self.play_start.setDecimals(6)
        self.play_start.setSingleStep(0.001)
        self.play_start.setObjectName(_fromUtf8("play_start"))
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(530, 470, 61, 31))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(500, 330, 20, 191))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(510, 500, 271, 51))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(770, 330, 20, 191))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(510, 320, 271, 20))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(790, 320, 261, 20))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.line_14 = QtGui.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(780, 330, 20, 201))
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.line_15 = QtGui.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(1040, 330, 20, 201))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_16 = QtGui.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(790, 520, 261, 20))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(810, 400, 101, 41))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.tick_quat = QtGui.QCheckBox(self.centralwidget)
        self.tick_quat.setGeometry(QtCore.QRect(850, 440, 131, 22))
        self.tick_quat.setObjectName(_fromUtf8("tick_quat"))
        self.tick_acc = QtGui.QCheckBox(self.centralwidget)
        self.tick_acc.setGeometry(QtCore.QRect(850, 470, 151, 22))
        self.tick_acc.setObjectName(_fromUtf8("tick_acc"))
        self.tick_marker = QtGui.QCheckBox(self.centralwidget)
        self.tick_marker.setGeometry(QtCore.QRect(850, 500, 96, 22))
        self.tick_marker.setObjectName(_fromUtf8("tick_marker"))
        self.line_17 = QtGui.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(500, 270, 561, 16))
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(500, 540, 561, 16))
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.line_19 = QtGui.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(1050, 280, 20, 271))
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.line_20 = QtGui.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(490, 280, 20, 271))
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(580, 160, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(520, 190, 81, 17))
        self.label_45.setText(_fromUtf8(""))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.tick_RVIZ = QtGui.QCheckBox(self.centralwidget)
        self.tick_RVIZ.setGeometry(QtCore.QRect(510, 190, 96, 22))
        self.tick_RVIZ.setObjectName(_fromUtf8("tick_RVIZ"))
        self.tick_show_markers = QtGui.QCheckBox(self.centralwidget)
        self.tick_show_markers.setGeometry(QtCore.QRect(510, 220, 131, 22))
        self.tick_show_markers.setObjectName(_fromUtf8("tick_show_markers"))
        self.markers_size = QtGui.QDoubleSpinBox(self.centralwidget)
        self.markers_size.setGeometry(QtCore.QRect(640, 220, 96, 27))
        self.markers_size.setDecimals(6)
        self.markers_size.setMaximum(0.2)
        self.markers_size.setSingleStep(0.001)
        self.markers_size.setObjectName(_fromUtf8("markers_size"))
        self.label_46 = QtGui.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(640, 170, 91, 61))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.line_21 = QtGui.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(500, 140, 251, 21))
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.line_22 = QtGui.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(500, 240, 251, 51))
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.line_23 = QtGui.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(490, 150, 20, 111))
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.line_24 = QtGui.QFrame(self.centralwidget)
        self.line_24.setGeometry(QtCore.QRect(740, 150, 20, 111))
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(930, 150, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.arduino_boot = QtGui.QCheckBox(self.centralwidget)
        self.arduino_boot.setGeometry(QtCore.QRect(800, 160, 101, 22))
        self.arduino_boot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arduino_boot.setObjectName(_fromUtf8("arduino_boot"))
        self.arduino_baud = QtGui.QSpinBox(self.centralwidget)
        self.arduino_baud.setGeometry(QtCore.QRect(930, 190, 113, 31))
        self.arduino_baud.setMinimum(9600)
        self.arduino_baud.setMaximum(999999999)
        self.arduino_baud.setObjectName(_fromUtf8("arduino_baud"))
        self.label_48 = QtGui.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(800, 190, 81, 31))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.arduino_port = QtGui.QLineEdit(self.centralwidget)
        self.arduino_port.setGeometry(QtCore.QRect(880, 230, 161, 31))
        self.arduino_port.setObjectName(_fromUtf8("arduino_port"))
        self.label_50 = QtGui.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(800, 230, 61, 31))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.line_25 = QtGui.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(780, 140, 281, 20))
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.line_26 = QtGui.QFrame(self.centralwidget)
        self.line_26.setGeometry(QtCore.QRect(780, 260, 281, 20))
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.line_27 = QtGui.QFrame(self.centralwidget)
        self.line_27.setGeometry(QtCore.QRect(1050, 150, 20, 121))
        self.line_27.setFrameShape(QtGui.QFrame.VLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.line_28 = QtGui.QFrame(self.centralwidget)
        self.line_28.setGeometry(QtCore.QRect(770, 150, 20, 121))
        self.line_28.setFrameShape(QtGui.QFrame.VLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(240, 450, 242, 71))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 2, 0, 1, 1)
        self.base_quat_x = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.base_quat_x.setDecimals(6)
        self.base_quat_x.setMinimum(-1.0)
        self.base_quat_x.setMaximum(1.0)
        self.base_quat_x.setSingleStep(0.001)
        self.base_quat_x.setObjectName(_fromUtf8("base_quat_x"))
        self.gridLayout.addWidget(self.base_quat_x, 2, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 2, 2, 1, 1)
        self.base_quat_y = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.base_quat_y.setDecimals(6)
        self.base_quat_y.setMinimum(-1.0)
        self.base_quat_y.setMaximum(1.0)
        self.base_quat_y.setSingleStep(0.001)
        self.base_quat_y.setObjectName(_fromUtf8("base_quat_y"))
        self.gridLayout.addWidget(self.base_quat_y, 0, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 0, 2, 1, 1)
        self.base_quat_z = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.base_quat_z.setDecimals(6)
        self.base_quat_z.setMinimum(-1.0)
        self.base_quat_z.setMaximum(1.0)
        self.base_quat_z.setSingleStep(0.001)
        self.base_quat_z.setObjectName(_fromUtf8("base_quat_z"))
        self.gridLayout.addWidget(self.base_quat_z, 2, 3, 1, 1)
        self.base_quat_w = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.base_quat_w.setDecimals(6)
        self.base_quat_w.setMinimum(-1.0)
        self.base_quat_w.setMaximum(1.0)
        self.base_quat_w.setSingleStep(0.001)
        self.base_quat_w.setObjectName(_fromUtf8("base_quat_w"))
        self.gridLayout.addWidget(self.base_quat_w, 0, 1, 1, 1)
        self.calibrate_file = QtGui.QLineEdit(self.centralwidget)
        self.calibrate_file.setGeometry(QtCore.QRect(130, 600, 221, 31))
        self.calibrate_file.setObjectName(_fromUtf8("calibrate_file"))
        self.label_52 = QtGui.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(200, 560, 191, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_51 = QtGui.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(20, 590, 101, 51))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.line_29 = QtGui.QFrame(self.centralwidget)
        self.line_29.setGeometry(QtCore.QRect(10, 630, 1041, 20))
        self.line_29.setFrameShape(QtGui.QFrame.HLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.line_30 = QtGui.QFrame(self.centralwidget)
        self.line_30.setGeometry(QtCore.QRect(10, 550, 361, 20))
        self.line_30.setFrameShape(QtGui.QFrame.HLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.line_31 = QtGui.QFrame(self.centralwidget)
        self.line_31.setGeometry(QtCore.QRect(0, 560, 20, 81))
        self.line_31.setFrameShape(QtGui.QFrame.VLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.calibration_saved_file = QtGui.QLineEdit(self.centralwidget)
        self.calibration_saved_file.setEnabled(True)
        self.calibration_saved_file.setGeometry(QtCore.QRect(610, 600, 221, 31))
        self.calibration_saved_file.setObjectName(_fromUtf8("calibration_saved_file"))
        self.line_33 = QtGui.QFrame(self.centralwidget)
        self.line_33.setGeometry(QtCore.QRect(370, 550, 681, 20))
        self.line_33.setFrameShape(QtGui.QFrame.HLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(620, 560, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(580, 590, 31, 51))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.line_36 = QtGui.QFrame(self.centralwidget)
        self.line_36.setGeometry(QtCore.QRect(1040, 560, 20, 81))
        self.line_36.setFrameShape(QtGui.QFrame.VLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.calibration_use_saved = QtGui.QCheckBox(self.centralwidget)
        self.calibration_use_saved.setGeometry(QtCore.QRect(870, 600, 141, 31))
        self.calibration_use_saved.setObjectName(_fromUtf8("calibration_use_saved"))
        self.line_37 = QtGui.QFrame(self.centralwidget)
        self.line_37.setGeometry(QtCore.QRect(1050, 20, 20, 121))
        self.line_37.setFrameShape(QtGui.QFrame.VLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.line_38 = QtGui.QFrame(self.centralwidget)
        self.line_38.setGeometry(QtCore.QRect(780, 130, 281, 20))
        self.line_38.setFrameShape(QtGui.QFrame.HLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.line_39 = QtGui.QFrame(self.centralwidget)
        self.line_39.setGeometry(QtCore.QRect(780, 10, 281, 20))
        self.line_39.setFrameShape(QtGui.QFrame.HLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName(_fromUtf8("line_39"))
        self.line_40 = QtGui.QFrame(self.centralwidget)
        self.line_40.setGeometry(QtCore.QRect(770, 20, 16, 121))
        self.line_40.setFrameShape(QtGui.QFrame.VLine)
        self.line_40.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_40.setObjectName(_fromUtf8("line_40"))
        self.label_49 = QtGui.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(870, 30, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.topic_1 = QtGui.QCheckBox(self.centralwidget)
        self.topic_1.setGeometry(QtCore.QRect(790, 70, 131, 22))
        self.topic_1.setObjectName(_fromUtf8("topic_1"))
        self.topic_2 = QtGui.QCheckBox(self.centralwidget)
        self.topic_2.setGeometry(QtCore.QRect(790, 100, 131, 22))
        self.topic_2.setObjectName(_fromUtf8("topic_2"))
        self.topic_3 = QtGui.QCheckBox(self.centralwidget)
        self.topic_3.setGeometry(QtCore.QRect(930, 70, 121, 22))
        self.topic_3.setObjectName(_fromUtf8("topic_3"))
        self.topic_4 = QtGui.QCheckBox(self.centralwidget)
        self.topic_4.setGeometry(QtCore.QRect(930, 100, 121, 22))
        self.topic_4.setObjectName(_fromUtf8("topic_4"))
        self.use_fast_mag_calib = QtGui.QCheckBox(self.centralwidget)
        self.use_fast_mag_calib.setGeometry(QtCore.QRect(390, 600, 171, 31))
        self.use_fast_mag_calib.setObjectName(_fromUtf8("use_fast_mag_calib"))
        self.imu_calib_id = QtGui.QSpinBox(self.centralwidget)
        self.imu_calib_id.setGeometry(QtCore.QRect(390, 570, 51, 27))
        self.imu_calib_id.setMinimum(1)
        self.imu_calib_id.setMaximum(8)
        self.imu_calib_id.setObjectName(_fromUtf8("imu_calib_id"))
        self.label_55 = QtGui.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(450, 560, 121, 51))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.button_letsgo.setText(_translate("MainWindow", "Start!", None))
        self.button_quit.setText(_translate("MainWindow", "Quit", None))
        self.label_2.setText(_translate("MainWindow", "IMU source", None))
        self.label_3.setText(_translate("MainWindow", "Mode", None))
        self.label_5.setText(_translate("MainWindow", "# of Markers", None))
        self.label_6.setText(_translate("MainWindow", "Main parameters", None))
        self.label_7.setText(_translate("MainWindow", "Modeling", None))
        self.label_8.setText(_translate("MainWindow", "Arm length [m]", None))
        self.label_9.setText(_translate("MainWindow", "Arm Radius [m]", None))
        self.label_11.setText(_translate("MainWindow", "2", None))
        self.label_12.setText(_translate("MainWindow", "3", None))
        self.label_13.setText(_translate("MainWindow", "8", None))
        self.label_10.setText(_translate("MainWindow", "1", None))
        self.label_14.setText(_translate("MainWindow", "4", None))
        self.label_18.setText(_translate("MainWindow", "IMU #", None))
        self.label_16.setText(_translate("MainWindow", "6", None))
        self.label_15.setText(_translate("MainWindow", "7", None))
        self.label_17.setText(_translate("MainWindow", "5", None))
        self.label_20.setText(_translate("MainWindow", "# of segments\n"
" between \n"
" [IMU #-1, \n"
" IMU #]", None))
        self.label_19.setText(_translate("MainWindow", "Position [m]", None))
        self.label_27.setText(_translate("MainWindow", "Marker #", None))
        self.label_21.setText(_translate("MainWindow", "2", None))
        self.label_31.setText(_translate("MainWindow", "5", None))
        self.label_23.setText(_translate("MainWindow", "8", None))
        self.label_29.setText(_translate("MainWindow", "6", None))
        self.label_24.setText(_translate("MainWindow", "1", None))
        self.label_30.setText(_translate("MainWindow", "7", None))
        self.label_25.setText(_translate("MainWindow", "4", None))
        self.label_22.setText(_translate("MainWindow", "3", None))
        self.label_26.setText(_translate("MainWindow", "Position [m]", None))
        self.label_35.setText(_translate("MainWindow", "Reorientation for IMUs quaternions", None))
        self.label_36.setText(_translate("MainWindow", "My Rosbag", None))
        self.label_37.setText(_translate("MainWindow", "Play", None))
        self.label_38.setText(_translate("MainWindow", "File", None))
        self.label_39.setText(_translate("MainWindow", "Record", None))
        self.label_40.setText(_translate("MainWindow", "File", None))
        self.label_41.setText(_translate("MainWindow", "Rate", None))
        self.label_42.setText(_translate("MainWindow", "Start [s]", None))
        self.label_43.setText(_translate("MainWindow", "Record topics:", None))
        self.tick_quat.setText(_translate("MainWindow", "Orientations", None))
        self.tick_acc.setText(_translate("MainWindow", "Accelerometers", None))
        self.tick_marker.setText(_translate("MainWindow", "Markers", None))
        self.label_44.setText(_translate("MainWindow", "Visualization", None))
        self.tick_RVIZ.setText(_translate("MainWindow", "Show RVIZ", None))
        self.tick_show_markers.setText(_translate("MainWindow", "Show Markers", None))
        self.label_46.setText(_translate("MainWindow", "Markers size \n"
" for RVIZ", None))
        self.label_47.setText(_translate("MainWindow", "Arduino", None))
        self.arduino_boot.setText(_translate("MainWindow", "  Boot                           ", None))
        self.label_48.setText(_translate("MainWindow", "Baud", None))
        self.label_50.setText(_translate("MainWindow", "Port", None))
        self.label_33.setText(_translate("MainWindow", "x", None))
        self.label_34.setText(_translate("MainWindow", "w", None))
        self.label_28.setText(_translate("MainWindow", "z", None))
        self.label_32.setText(_translate("MainWindow", "y", None))
        self.label_52.setText(_translate("MainWindow", "Calibrate an IMU", None))
        self.label_51.setText(_translate("MainWindow", "Save to this file", None))
        self.label_53.setText(_translate("MainWindow", "Use previous calibration", None))
        self.label_54.setText(_translate("MainWindow", "File", None))
        self.calibration_use_saved.setText(_translate("MainWindow", "Load calibration", None))
        self.label_49.setText(_translate("MainWindow", "rostopic echo", None))
        self.topic_1.setText(_translate("MainWindow", "CheckBox", None))
        self.topic_2.setText(_translate("MainWindow", "CheckBox", None))
        self.topic_3.setText(_translate("MainWindow", "CheckBox", None))
        self.topic_4.setText(_translate("MainWindow", "CheckBox", None))
        self.use_fast_mag_calib.setText(_translate("MainWindow", "Use fast mag calib", None))
        self.label_55.setText(_translate("MainWindow", "IMU identifier", None))

